import AppError from '@shared/errors/AppError';

import { NextFunction, Request, Response } from 'express';
import { verify } from 'jsonwebtoken';
import authconfig from '@config/auth';

//the middlewares has minimu 3 parametes
export default function isAuthenticated(
  request: Request,
  response: Response,
  next: NextFunction,
): void {
  const authHeader = request.headers.authorization;
  if (!authHeader) {
    throw new AppError('JWT Token is missing.');
  }

  // Bearer  UJJHSJSJSISISIJSISJSJS

  const [, token] = authHeader.split(' '); //or const token = authHeader.split(' ')[1];

  //verify if the token was generated by our app ou is valid

  try {
    const decodeToken = verify(token, authconfig.jwt.secret);
    return next();
  } catch {
    throw new AppError('Invalid JWT Token');
  }
}
